[package]
name = "znotify-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0.18", features = ["derive", "cargo", "std"] }
tokio = { version = "1.21.2", features = ["rt-multi-thread"] }
znotify = "0.0.3"

[profile.release]
lto = true

[[bin]]
name = "znotify"
path = "src/main.rs"