[package]
name = "znotify-cli"
version = "0.1.3"
edition = "2021"
description = "Send notification to ZNotify server"
authors = ["Zxilly <zxilly@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ZNotify/cli"
repository = "https://github.com/ZNotify/cli"
categories = ["command-line-interface"]


[dependencies]
clap = { version = "4.0.29", features = ["derive", "cargo", "std"] }
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
znotify = "0.1.1"
dirs = "4.0.0"
toml_edit = { version = "0.16.0", features = ["easy"] }
self_update = "0.32.0"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10.44", features = ["vendored"] }


[profile.release]
lto = true
opt-level = 3

[[bin]]
name = "znotify"
path = "src/main.rs"

[package.metadata.deb]
section = "utility"
priority = "optional"
license-file = ["LICENSE", "4"]
assets = [
    ["target/release/znotify", "usr/bin/znotify", "755"],
    ["README.md", "usr/share/doc/znotify/README", "644"],
]